#<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>DealPlug Naija</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0; padding: 0;
      background: #f0f4f8;
      color: #333;
    }
    header {
      background: #004aad;
      color: white;
      padding: 20px;
      text-align: center;
    }
    h1 {
      margin: 0;
      font-size: 2.5em;
    }
    main {
      max-width: 900px;
      margin: 20px auto;
      padding: 0 20px;
    }
    section {
      margin-bottom: 40px;
    }
    .products {
      display: flex;
      flex-wrap: wrap;
      gap: 20px;
    }
    .product {
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 6px rgba(0,0,0,0.1);
      width: calc(33% - 13px);
      padding: 15px;
      box-sizing: border-box;
      text-align: center;
    }
    .product img {
      max-width: 100%;
      height: auto;
      border-radius: 4px;
    }
    .product h3 {
      margin: 10px 0 5px;
      font-size: 1.1em;
      color: #004aad;
    }
    .product p {
      margin: 0;
      font-weight: bold;
      color: #27ae60;
    }
    footer {
      background: #222;
      color: #aaa;
      text-align: center;
      padding: 15px;
      font-size: 0.9em;
    }
    a.phone-link {
      color: #004aad;
      font-weight: bold;
      text-decoration: none;
    }
    @media (max-width: 700px) {
      .product {
        width: calc(50% - 10px);
      }
    }
    @media (max-width: 450px) {
      .product {
        width: 100%;
      }
    }
  </style>
</head>
<body>
  <header>
    <h1>DealPlug Naija</h1>
    <p>Your trusted reselling partner in Oron, Akwa Ibom</p>
  </header>

  <main>
    <section>
      <h2>Featured Products</h2>
      <div class="products">
        <div class="product">
          <img src="https://via.placeholder.com/200x150?text=Smart+TV" alt="Smart TV" />
          <h3>Smart TV</h3>
          <p>₦150,000</p>
        </div>
        <div class="product">
          <img src="https://via.placeholder.com/200x150?text=Men's+T-Shirt" alt="Men's T-Shirt" />
          <h3>Men's T-Shirt</h3>
          <p>₦3,000</p>
        </div>
        <div class="product">
          <img src="https://via.placeholder.com/200x150?text=Microwave+Oven" alt="Microwave Oven" />
          <h3>Microwave Oven</h3>
          <p>₦40,000</p>
        </div>
      </div>
    </section>

    <section>
      <h2>Product Catalog</h2>

      <h3>Electronics</h3>
      <ul>
        <li>Smart TV — ₦150,000</li>
        <li>Bluetooth Speaker — ₦12,000</li>
        <li>Laptop — ₦250,000</li>
      </ul>

      <h3>Fashion</h3>
      <ul>
        <li>Men's T-Shirt — ₦3,000</li>
        <li>Women's Dress — ₦7,000</li>
        <li>Sneakers — ₦15,000</li>
      </ul>

      <h3>Home Appliances</h3>
      <ul>
        <li>Microwave Oven — ₦40,000</li>
        <li>Electric Kettle — ₦5,000</li>
        <li>Refrigerator — ₦120,000</li>
      </ul>

      <h3>Phones & Accessories</h3>
      <ul>
        <li>Smartphone — ₦80,000</li>
        <li>Phone Case — ₦1,500</li>
        <li>Power Bank — ₦6,000</li>
      </ul>

      <h3>Beauty Products</h3>
      <ul>
        <li>Face Cream — ₦4,000</li>
        <li>Perfume — ₦10,000</li>
        <li>Hair Oil — ₦3,500</li>
      </ul>
    </section>

    <section>
      <h2>Contact Us</h2>
      <p>Call or WhatsApp us at: <a class="phone-link" href="tel:+2347043996851">07043996851</a></p>
      <p>Or send us a message on WhatsApp: <a class="phone-link" href="https://wa.me/2347043996851" target="_blank">Chat on WhatsApp</a></p>
    </section>
  </main>

  <footer>
    &copy; 2025 DealPlug Naija — All rights reserved.
  </footer>
</body>
</html> Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
